name: nerd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - certifi==2026.1.4
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.1.1
      - cryptography==46.0.4
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - h5py==3.11.0
      - idna==3.11
      - importlib-resources==6.4.5
      - ipdb==0.13.13
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.13.0.90
      - packaging==26.0
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==10.4.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycollada==0.9.2
      - pycparser==2.23
      - pygame==2.1.0
      - pyglet==2.1.6
      - pyparsing==3.1.4
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rl-games==1.6.1
      - rsa==4.9.1
      - sentry-sdk==2.51.0
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tomli==2.4.0
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - trimesh==4.7.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - wandb==0.12.21
      - warp-lang==1.8.0
      - wcwidth==0.5.2
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/maros/miniconda3/envs/nerd
